### ISSUE TITLE
Use platform-independent concurrency

### ISSUE THREAD

**Issue by dominicm00** [dominicm00/ham#29]
Instead of manually implementing concurrency via `platform::PlatformProcessDelegate`, we should use `std::system`.

- [ ] Replace `platform::PlatformProcessDelegate` and `process::Process` with `std::system`.

**Comment by waddlesplash** [comment]
Not sure what this issue is referring to. PlatformProcessDelegate launches processes and then retrieves status, I don't think you can do that in a platform-independent way?

However, you can definitely improve things here by using `posix_spawn` instead of `fork/exec` in PlatformProcessDelegate Unix version; this is much faster on Linux (and in some but not all cases on Haiku, but it's at least not slower) and allows for direct control over execution environment and other things.

**Comment by dominicm00** [comment]
> Not sure what this issue is referring to. PlatformProcessDelegate launches processes and then retrieves status, I don't think you can do that in a platform-independent way?

I think my comment about `std::thread` was misguided here, but doesn't [`system`](https://en.cppreference.com/w/cpp/utility/program/system) do exactly this?

> However, you can definitely improve things here by using `posix_spawn` instead of `fork/exec` in PlatformProcessDelegate Unix version; this is much faster on Linux (and in some but not all cases on Haiku, but it's at least not slower) and allows for direct control over execution environment and other things.

Ok, thanks for the tip!
